* Kosz
Declarative Emacs package builder.

It created to provide the Leiningen like expirience for developing Emacs
packages with comfortable user interface with interactive functions.

Kosz is not a package manager. It doesn't manages packages and their
dependencies. It creates tar archives what can be installed by ~package.el~.

For information about how to use Kosz read the manual.


** Requirements outside Emacs
Requirements from the system for package working.

- GNU Info - for building .texi manuals.
- Tar - for packing files (build-in Emacs tar support is very programming
  unfrendly).

# The end of README if you read this from package-description buffer.



** Building and installation
Kosz is multi-file package what means it includes several Emacs Lisp files and
info manual. For simplifying the building there is the build.el Emacs Lisp
script. It will run new Emacs instance, load Kosz core files and build fully
functional Kosz package.

For building is needed to eval ~build.el~ file.

- From emacs: open ~build.el~ file and do ~M-x eval-buffer~.
- From shell: ~$ emacs --batch --quick --script /path/to/build.el~.

It will create ~build/kosz-*-.tar~ file. Install it by ~package.el~ like
~M-x package-install-from-file~ or extract and add extracted directory to
~load-path~ list.


** License
Copyright © 2023  Lämppi Lütti <lamppilutti@gmail.com>

Distributed under the GNU General Public License v3.0 or later.
